### ISSUE TITLE
Strange parser failures in oasis

### ISSUE THREAD

**Issue by ondracka** [ondracka/nomad-parser-openmx#18]
I've deployed the current parser in our oasis and running re-process on the whole database brings some issues. Specifically
```
"root":{
"errors":string"parser failed with exception"
"event":string"task failed"
"task":string"parsing"
"proc":string"Calc"
"process":string"re_process_calc"
"tasks_status":string"FAILURE"
"error":string"ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U8'), dtype('<U8')) -> dtype('<U8')"
"parser":string"parsers/openmx"
"step":string"parsers/openmx"
"logger":string"nomad.processing"
"exception":string"Traceback (most recent call last): File "/app/nomad/processing/data.py", line 466, in parsing self._parser_results, logger=logger) File "/usr/local/lib/python3.7/site-packages/openmxparser/parser.py", line 209, in parse system.lattice_vectors = np.array(cell).reshape(3, 3) * units.angstrom File "/usr/local/lib/python3.7/site-packages/pint/unit.py", line 292, in __array_ufunc__ **kwargs, File "/usr/local/lib/python3.7/site-packages/pint/quantity.py", line 1638, in __array_ufunc__ return numpy_wrap("ufunc", ufunc, inputs, kwargs, types) File "/usr/local/lib/python3.7/site-packages/pint/numpy_func.py", line 904, in numpy_wrap return handled[name](*args, **kwargs) File "/usr/local/lib/python3.7/site-packages/pint/numpy_func.py", line 295, in implementation result_magnitude = func(*stripped_args, **stripped_kwargs) numpy.core._exceptions._UFuncNoLoopError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U8'), dtype('<U8')) -> dtype('<U8')"
"timestamp":string"2021-05-28 00:57.29"
"level":string"ERROR"
```
The problem is that this is not reproducible when running the parser standalone with nomad parse (even when running from the container). However, rerunning re-process on one seleted upload after the full re-process will reproduce this. However, restarting oasis will fix everything again and subsequent re-process will succeed.

**Comment by ondracka** [comment]
This might not be our bug, but rather a bug in the nomad itself, but tracking here for now.
